name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install htmlhint stylelint
      - name: Run HTML Lint
        run: npx htmlhint "src/**/*.html"
      - name: Run CSS Lint
        run: npx stylelint "styles/**/*.css"
